sudo: false

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
      - boost-latest
      
    packages:
      - cmake
      - cmake-data
      - clang-5.0
      - libboost1.55-all-dev
      - valgrind


before_install:
  - export CXX="clang++-5.0"
  - export CC="clang-5.0"

install:
  - ./buildDeps.sh
  - pip install --user cpp-coveralls
  
script: 
  - ./buildFromDeps.sh
  - cd Build
  - make test
  - ctest -T Memcheck
  - cd ..
  - COVERALLS_FLAGS="-e src/publisherSpeed.cpp -e src/dummy.cpp" ./deps/CMakeUtils/travis/doCoverage.sh
